=== phoebius/doc/dtd/index.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright (c) 2009 phoebius.org
 *
 * All rights reserved.
 *
 *************************************************************************************************
-->

<!ENTITY % reference.class "ref|doc|include">

<!--
	Resulting items are ordered wrt the definition
-->
<!ELEMENT index (%reference.class;)?>

	<!-- 
		Link to an xml document that implements dtd/document.dtd.
		This document specifies the document title by itself
	-->
	<!ELEMENT doc (%reference.class;)*>
	<!ATTLIST doc
		xml			CDATA #REQUIRED
	>
	
	<!-- 
		Absolute link to any location
	-->
	<!ELEMENT ref (%reference.class;)*>
	<!ATTLIST ref
		name		CDATA #REQUIRED
		link		CDATA #REQUIRED
	>
	
	<!-- 
		Include an xml document that implements dtd/index.dtd
	-->
	<!ELEMENT include EMPTY>
	<!ATTLIST include
		xml			CDATA #REQUIRED
	>

=== phoebius/doc/xml/site/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright (c) 2009 phoebius.org
 *
 * All rights reserved.
 *
 *************************************************************************************************
-->

<!DOCTYPE index SYSTEM "../../dtd/index.dtd">

<index site-part="Support">
	<doc xml="/support/support.xml" location="/support/">
		<include xml="support/index.xml" prefix="support"/>
	</doc>
	<doc xml="highlights.xml"></doc>
	<doc xml="roadmap.xml"></doc>
	<doc xml="about.xml" site-part="About"></doc>
	<doc xml="download.xml" site-part="Download"></doc>
	<doc xml="sitemap.xml"></doc>
</index>

=== phoebius/doc/xml/site/support/manual/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright (c) 2009 Scand Ltd.
 *
 * All rights reserved.
 *
 *************************************************************************************************
-->

<!DOCTYPE index SYSTEM "../../../../dtd/index.dtd">

<index>
 <doc xml="manual.xml" location=""/>
 <doc xml="basics.xml"/>
 <doc xml="configuration.xml"/>
 <doc xml="application.xml"/>
 <doc xml="model.xml"/>
 <doc xml="codegen.xml"/>
<!-- <doc xml="querying-entities.xml"/>
 <doc xml="routers.xml"/>
 <doc xml="controllers.xml"/>
 <doc xml="presentation-logic.xml"/>
 -->
	<ref link="/support/manual/use-cases/" name="Use-cases">
	 <include xml="use-cases/index.xml" prefix="use-cases"></include>
	</ref>
 
</index>
